### ISSUE TITLE
List of found bugs

### ISSUE THREAD

**Issue by TelmoMS** [InteraactionGroup/VisualSceneDisplay#7]
The canvas element doesn't resize with the main image and always stays the same size. **fixed**

The popup to create an hotspot pops multiple times after creating the first one (Possibly due to creating a new listener every time).

When importing a bad .json file, the code doesn't detect it and it may bug the entire application.

**Comment by kuhlkrein** [comment]
also we should fix the jasmines issues and "no providers issue"

**Comment by kuhlkrein** [comment]
Jasmine issue and "no providers issue" **fixed** 
The popup to create an hotspot pops multiple times after creating the first one (Possibly due to creating a new listener every time). **fixed**

**Comment by kuhlkrein** [comment]
When importing a bad .json file, the code doesn't detect it and it may bug the entire application. **fixed**
